const ACTION_TYPES = {
  SET_LOADING_TRUE: "SET_LOADING_TRUE",
  SET_LOADING_FALSE: "SET_LOADING_FALSE",
  SET_SURAH_LIST: "SET_SURAH_LIST",
  SET_CURRENT_MUROTTAL: "SET_CURRENT_MUROTTAL",
  SET_CURRENT_PLAY_SURAH_DATA: "SET_CURRENT_PLAY_SURAH_DATA",
  MUROTTAL_AUDIO_TOGGLE: "MUROTTAL_AUDIO_TOGGLE",
  SET_CURRENT_AYAT_LIST: "SET_CURRENT_AYAT_LIST",
  SET_DAFTAR_AYAT_TOGGLE: "SET_DAFTAR_AYAT_TOGGLE",
  TOGGLE_NAV: "TOGGLE_NAV",
};

export default ACTION_TYPES;
